### PR TITLE
fix (MSSQL): use TRY_CAST only in 2012 or newer

### LINKED ISSUE #37: TRY_CAST not supported by sql server 2008
https://github.com/keboola/db-writer-mssql/blob/76f919fc14d5b946948843d6ee3951e9375a6a3f/src/Writer/MSSQL.php#L138

Uses TRY_CAST, but that isn't supported in sql server 2008
https://docs.microsoft.com/en-us/sql/t-sql/functions/try-cast-transact-sql?view=sql-server-2017

### PR DESCRIPTION
**Pull request by MiroCillik**
FIXES https://github.com/keboola/db-writer-mssql/issues/37

### CODE REVIEW

**Comment by MiroCillik** [comment]
It's slowly turning into "zarovka" 💡 in here :) 

Wanted to fix this:
https://travis-ci.org/keboola/db-writer-mssql/builds/548595511
```
Fatal error: Uncaught PHP_CodeSniffer\Exceptions\RuntimeException: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /code/vendor/squizlabs/php_codesniffer/src/Files/File.php on line 1351 in /code/vendor/squizlabs/php_codesniffer/src/Runner.php:562
```

So I made composer updated... Fixed the codestyle issues but now I need to merge and deploy this little fix in common https://github.com/keboola/db-writer-common/pull/26 :)

**Comment by MiroCillik** [comment]
So the main thing is this function https://github.com/keboola/db-writer-mssql/pull/38/files#diff-920ea52a3e9af6a22ca8bef264fb23bcR159

The rest is just update of deps and codestyle.

I should probably split it into two PR's what you think @pivnicek ?

**Comment by MiroCillik** [comment]
I've created a separate PR for the updates, that one should be merged first https://github.com/keboola/db-writer-mssql/pull/39

File: src/Writer/MSSQL.php [hunk 1]
```diff
@@ -135,7 +135,8 @@ public function write(CsvFile $csv, array $table): void
             if (!empty($col['nullable'])) {
                 $srcColName = sprintf("NULLIF(%s, '')", $colName);
             }
-            $column = sprintf('TRY_CAST(%s AS %s%s) as %s', $srcColName, $type, $size, $colName);
+            $column = $this->bcpCast($srcColName, $type, $size, $colName, $this->dbParams['tdsVersion']);
```
Comment (pivnicek) [inline src/Writer/MSSQL.php]: I don't understand where does this tdsVersion parameter come from?  Was it always there I guess?

why not use a query to get the version instead of relying on user input?  
(like https://github.com/keboola/db-extractor-mssql/blob/master/src/Keboola/DbExtractor/Extractor/MSSQL.php#L30)

**Review by pivnicek — COMMENTED** [review]
I'm just not sure why use a parameter instead of letting the DB tell you what version it is.

File: src/Writer/MSSQL.php (hunk 1 above)
Comment (MiroCillik) [reply src/Writer/MSSQL.php]: Yeah you're right. I'll query the DB. This parameter was always there, but it's not used now.

Comment (MiroCillik) [reply src/Writer/MSSQL.php]: @pivnicek wouldn't there be a problem with permissions for existing configurations? 
That the DB user in the configuration, don't have rights ti access the "SERVERPROPRTY" stuff?

**Comment by tomasfejfar** [comment]
The underlying issue of the "continue" is that the PHP version is not locked in Dockerfile. So we'll get 7.4 as soon as it's released. 

Also the megadependencyupdate issue could be prevented by using `composer update vendor/package --with-dependencies`...

**Comment by MiroCillik** [comment]
Yeah, maybe locking on minor version would be more reasonable.

Sure, I just wanted to update all dependencies when at it ;)

File: src/Writer/MSSQL.php (hunk 1 above)
Comment (pivnicek) [reply src/Writer/MSSQL.php]: Shouldn't be, never happened on the ex.  I think this system info is available to all users.

Comment (MiroCillik) [reply src/Writer/MSSQL.php]: OK, so it is fine like this? There is now no test for the older version of the server though.

**Comment by tomasfejfar** [comment]
@MiroCillik, [client is waiting for this](https://keboola.zendesk.com/agent/tickets/10790), so could you please "hotfix" the issue by fixing the version in Dockerfile to 7.2 and ship it ASAP. We can deal with updated dependencies in a proper manner later. 

Also please reply there when the issue is solved. Thanks.
